steps:
- id: "Build WAR files using Maven"
  name: maven
  entrypoint: /bin/bash
  args:
    - -c
    - |
      # Going to workspace where code is present
      echo Hello
      chmod +x build_script.sh
      ./build_script.sh
      echo *************root**********************
      ls
      echo *************springboot-cont-a folder**********************
      ls ../springboot-cont-a
      echo *************springboot-cont-a/target folder**********************
      ls ../springboot-cont-a/target
      echo *************workspace folder**********************
      ls /workspace
- id: "Building docker image for container a"
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t',
          'gcr.io/project-for-tf-cicd-kube/cont-a:v2',
          '-f', '/workspace/Tomcat-working/DockerfileContA', '/workspace/Tomcat-working/' ]
- id: "Building docker image for container b"
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t',
          'gcr.io/project-for-tf-cicd-kube/cont-b:v2',
          '-f', '/workspace/Tomcat-working/DockerfileContB', '/workspace/Tomcat-working/' ]
- id: "Building docker image for container c"
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t',
          'gcr.io/project-for-tf-cicd-kube/cont-c:v2',
          '-f', '/workspace/Tomcat-working/DockerfileContC', '/workspace/Tomcat-working/' ]
- id: "Building docker image for container d"
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t',
          'gcr.io/project-for-tf-cicd-kube/cont-d:v2',
          '-f', '/workspace/Tomcat-working/DockerfileContD', '/workspace/Tomcat-working/' ]
images:
- 'gcr.io/project-for-tf-cicd-kube/cont-a:v2'
- 'gcr.io/project-for-tf-cicd-kube/cont-b:v2'
- 'gcr.io/project-for-tf-cicd-kube/cont-c:v2'
- 'gcr.io/project-for-tf-cicd-kube/cont-d:v2'
# artifacts:
#   objects:
#     location: 'gs://war-file-bucket/$PROJECT_ID'
#     paths: ['/workspace/*.war']
options:
  logging: CLOUD_LOGGING_ONLY
