steps:
- id: "Build WAR files using Maven"
  name: maven
  entrypoint: /bin/bash
  args:
    - -c
    - |
      # Going to workspace where code is present
      echo Hello
      chmod +x build_script.sh
      ./build_script.sh
      echo *************root**********************
      ls
      echo *************springboot-cont-a folder**********************
      ls ./springboot-cont-a
      echo *************springboot-cont-a/target folder**********************
      ls ./springboot-cont-a/target
      echo *************workspace folder**********************
      ls /workspace
artifacts:
  objects:
    location: 'gs://war-file-bucket/$PROJECT_ID'
    paths: ['/workspace/*.war']
options:
  logging: CLOUD_LOGGING_ONLY
